// Canonical framework name mappings (lowercase -> proper casing)
const FRAMEWORK_MAP: Record<string, string> = {
  accessibility: 'Accessibility',
  activitykit: 'ActivityKit',
  alarmkit: 'AlarmKit',
  appintents: 'App Intents',
  appkit: 'AppKit',
  arkit: 'ARKit',
  avfoundation: 'AVFoundation',
  avkit: 'AVKit',
  callkit: 'CallKit',
  carplay: 'CarPlay',
  clockkit: 'ClockKit',
  cloudkit: 'CloudKit',
  combine: 'Combine',
  contacts: 'Contacts',
  coreaudio: 'Core Audio',
  corebluetooth: 'Core Bluetooth',
  coredata: 'Core Data',
  coregraphics: 'Core Graphics',
  coreimage: 'Core Image',
  corelocation: 'Core Location',
  coreml: 'Core ML',
  coremotion: 'Core Motion',
  corenfc: 'Core NFC',
  createml: 'Create ML',
  cryptokit: 'CryptoKit',
  eventkit: 'EventKit',
  foundation: 'Foundation',
  gamekit: 'GameKit',
  healthkit: 'HealthKit',
  homekit: 'HomeKit',
  lockedcameracapture: 'LockedCameraCapture',
  mapkit: 'MapKit',
  metal: 'Metal',
  musickit: 'MusicKit',
  naturallanguage: 'Natural Language',
  network: 'Network',
  photokit: 'PhotoKit',
  photos: 'Photos',
  photosui: 'PhotosUI',
  pushkit: 'PushKit',
  realitykit: 'RealityKit',
  scenekit: 'SceneKit',
  security: 'Security',
  sirikit: 'SiriKit',
  speech: 'Speech',
  spritekit: 'SpriteKit',
  storekit: 'StoreKit',
  swift: 'Swift',
  swiftdata: 'SwiftData',
  swiftui: 'SwiftUI',
  tipskit: 'TipKit',
  uikit: 'UIKit',
  vision: 'Vision',
  visionkit: 'VisionKit',
  weatherkit: 'WeatherKit',
  webkit: 'WebKit',
  widgetkit: 'WidgetKit',
  watchkit: 'WatchKit',
}

export function normalizeFramework(name: string): string {
  if (!name) return ''
  const lower = name.trim().toLowerCase()
  return FRAMEWORK_MAP[lower] ?? name.charAt(0).toUpperCase() + name.slice(1)
}
